### ISSUE TITLE
[Req]: Text-to-Speech

### ISSUE THREAD

**Issue by arnu515** [developertools-tech/developertools.tech#107]
### Explain the proposed feature

Allow the user to input some text and get a robotic text-to-speech version of it. The user can then download the speech audio generated. Everything will be generated in the browser itself using the [SpeechSynthesis](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis) Web API.

### Explain the possible use cases for the feature

This could be useful to developers who want to quickly add some voice lines to their app. This speech synthesis tool will be free, since it uses the developer's built in speech synthesis tool to create text-to-speech lines, instead of relying on an outside service.

**Comment by arnu515** [comment]
If possible, I would like to be assigned this issue please.

**Comment by dlford** [comment]
> If possible, I would like to be assigned this issue please.

Sure, all yours!

**Comment by arnu515** [comment]
I will not be able to work on this one either. I'm sorry.
