### ISSUE TITLE
[Bug]: CopyLeft date is stuck on 2022

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#110]
### What happened?

CopyLeft date in footer shows 2022

### What should have happened?

CopyLeft date in footer should be dynamic and show the current year

### What browsers are you seeing the problem on?

Chrome

### Version

117.0.5938.149

### Relevant log output

```sh
N/A
```

## Deliverables

- Change the code for the CopyLeft date to make it dynamically show the current year at all times.

**Comment by sagormahtab** [comment]
Hey there @dlford,
I'd like to resolve this issue. Can you please assign this task to me?

**Comment by manish-bhukar** [comment]
Please assign me this task.

**Comment by dlford** [comment]
@sagormahtab all yours!

@manish-bhukar so sorry, @sagormahtab was first
