### ISSUE TITLE
[Req]: Translate language menu

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#116]
### Explain the proposed feature

The language menu currently only lists all languages by their short code. It would be better to list them as the name of the language in that particular language for better comprehension.

Current language list:

![ksnip_20231014-125445](https://github.com/developertools-tech/developertools.tech/assets/22881850/e19d445a-5cfd-4f8d-b21d-5f596b3d83a3)

### Explain the possible use cases for the feature

This would enable folks who don't speak english and/or don't know what the language codes mean to easily find the language they speak

### Any other details you would like to provide?

**Deliverables**:

- Add a translation namespace for the language menu
- Display all languages in english using the translation namespace

**Optional**:

- Add translations for each language that you can other than english

**Comment by burhanharoon** [comment]
Hey @dlford, can you assign me to work on that feature? I'm excited to get started with the development. Thanks a bunch!

**Comment by dlford** [comment]
@burhanharoon all yours!

**Comment by burhanharoon** [comment]
Just a clarification do we want languages listed in their locales like this
- When language Amharic 'am' is selected the language dropdown displays this:
```
{
  "en": "እንግሊዝኛ",
  "es": "ስፓኒሽ",
  "hi": "ህንዲ",
  "ja": "ጃፓንኛ",
  "pt": "ፖርቹጋልኛ",
  "bn": "በንጋሊ",
  "de": "ጀርመን",
  "sw": "ስዋሂሊ",
  "pl": "ፖሊሽ",
  "am": "አማርኛ",
  "it": "ጣሊያንኛ",
  "vi": "ቪትናምኛ"
}
```
and it goes on for other languages too..


- Or should it be like this in all the cases?
```
{
  "en": "English",
  "es": "Español",
  "hi": "हिन्दी",
  "ja": "日本語",
  "pt": "Português",
  "bn": "বাংলা",
  "de": "Deutsch",
  "sw": "Kiswahili",
  "pl": "Polski",
  "am": "አማርኛ",
  "it": "Italiano",
  "vi": "Tiếng Việt"
}
```

What do you suggest?

**Comment by dlford** [comment]
@burhanharoon Great question and thanks for asking, I'm inclined to think each language should be written in its own language (Option two in your examples).

Unless you can see any issues with that?

**Comment by dlford** [comment]
Also, if you don't mind updating the `contributing.md` file on how to add a new language with the translation, that'd be great!

**Comment by burhanharoon** [comment]
> Also, if you don't mind updating the `contributing.md` file on how to add a new language with the translation, that'd be great!

Sure, will do!

**Comment by dlford** [comment]
> I believe it exists in `contributing.md` under the `Basic Example` section. It is well-written and according to the project structure. Let me know if you want something else.

Sorry if I wasn't totally clear on that, would you mind just putting a note about adding the translated language name under [Adding a Language](https://github.com/developertools-tech/developertools.tech/blob/main/CONTRIBUTING.md#add-a-language)?

**Comment by burhanharoon** [comment]
```
module.exports = {
  i18n: {
    // ...
    locales: ['en', 'ja', 'pt-BR', 'YOUR_LOCALE_HERE'], // SHOULD I UPDATE THAT?_
  },
  // ...
};
```

**Comment by dlford** [comment]
@burhanharoon it's ok as is, don't worry about it.
