### ISSUE TITLE
Co-Maintainers Wanted

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#117]
This project is a valuable resource for developers (at least that is my hope and goal), but I alone shouldn't be making all of the decisions, nor do I have the time to work on it as much as I'd like.

I'm looking for two to three co-maintainers to spread out the workload and help with decision making.

If you are interested, please comment on this issue or reach out to me personally by using the contact form at https://www.dlford.io

**Comment by Pavan-Sai-padavala** [comment]
i would be interested to work with you @dlford
