### ISSUE TITLE
[Req]: Color Conversion Tool

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#12]
### Explain the proposed feature

Tool for converting colors between Hex/RGB/HSL/etc. A color picker would also be nice.

**Comment by kubahasek** [comment]
Hi! I think I can do this, could I get it assigned and I'll give it a shot :)

**Comment by dlford** [comment]
@kubahasek Awesome! Feel free to reach out if you have questions

**Comment by kubahasek** [comment]
@dlford 

Hi, as much as I hate to annoy you, I am having some issues making the tool. I have gotten it to work with a color picker and as well as when you enter the HEX value, but I cannot get it to react to any other inputs properly at least.

Could you please take a look at https://github.com/kubahasek/developertools.tech/tree/color-tool and possibly point me to what's wrong? Thanks a lot

**Comment by dlford** [comment]
@kubahasek of course, not a problem at all! I'll take a look soon and get back to you.

**Comment by dlford** [comment]
@kubahasek great job on this so far!

Looks like we aren't catching the errors here - https://github.com/kubahasek/developertools.tech/blob/color-tool/pages/colors.tsx#L88

I think a better approach would be to set up all the `onChange` calls to just assign the value for that input and use a `useEffect` hook to update the others based on which input was changed, or show the user error if the input is not valid.

Alternatively you could use `defaultValue` instead of `value` on the inputs so their values will change when typed into, and just catch the errors.

Here's an example of a similar approach - https://github.com/developertools-tech/developertools.tech/blob/main/components/base64/Base64InputOutput.tsx#L38-L75

Feel free to reach out if you need more information!

**Comment by kubahasek** [comment]
@dlford 

Hello! I have reshuffled the logic a little bit, but I am still having issues. 

[LINK](https://github.com/kubahasek/developertools.tech/blob/a11d41f84517ce79d97583a99b16da0e77866395/pages/colors.tsx#L117) The main problem is with this line (only there to demonstrate). If I use value, it works properly when the others change but it's practically impossible to change what's in the input because it holds the structure set out in the value (h, s, l).

I have tried different approaches, but if I use default value then the inputs aren't obviously reacting to the others changing.

**Comment by dlford** [comment]
@kubahasek I see, I'll take a look and see what I can figure out.

**Comment by dlford** [comment]
@kubahasek You're on the right track, just use `value` instead of  `defaultValue` since you're now handling the errors and still setting the value on change.

I think all that's left is to update the color picker when the text inputs change, and add tests.

**Comment by kubahasek** [comment]
@dlford I know that, but I will need to do some more digging. As soon as I set `value={r, g, b}` it becomes impossible to change the values in the inputs properly, so I need to look into that

As for tests, I will do my best, but I've never written them 😅

**Comment by dlford** [comment]
@kubahasek Ah I see, let me know if you still need help! As for the tests have a look at some of the other tests, I think you'll find it's easier than you might think, but I'm happy to help with that too if needed 😁

**Comment by kubahasek** [comment]
@dlford 

I think I've exhausted all my options to try and make it work properly. The code should now be in the state where everything works properly apart from the editing really, which still acts all funky whenever you try to manually input a color.

As for tests, I haven't yet started those, as I assume that should be done after the page is actually done.

**Comment by dlford** [comment]
@kubahasek you are correct about the tests, go ahead and submit a PR if you haven't yet and mark it as a draft, I'll take a look and see what I can figure out.
