### ISSUE TITLE
[Req]: Text Diff Tool

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#22]
### Explain the proposed feature

A tool to show the difference between two chunks of text. 

### Explain the possible use cases for the feature

This would be used to determine what has changed in two versions of a file (or any piece of text) that are not stored in version control, or to verify that they are the same.

### Any other details you would like to provide?

Some ideas to play with but not necessarily requirements - controls for displaying the diff side by side or unified, blank space sensitivity, feel free to get creative here if you like.

**Comment by AnkitaMalik22** [comment]
please assign me ! I would love to do .

**Comment by dlford** [comment]
@AnkitaMalik22 all yours!
