### ISSUE TITLE
[Req]: Query String Tool

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#24]
### Explain the proposed feature

A tool for working with URL query strings (e.g. `https://somesite.com/?querystring=somevalue&anotherquerystring=somethingelse`).

### Explain the possible use cases for the feature

Query strings can be very long and difficult to parse when debugging complex API calls, having a more human readable format to parse and modify for testing can save a lot of time.

### Any other details you would like to provide?

The tool should at the very least convert a query string to a list of key/values and build a query string from a list of key/values.

For example, the URL above would output the following

```txt
querystring=somevalue
anotherquerystring=somethingelse
```

Additional features that are not required might include:
- Converting to alternate formats such as JSON
- Supporting edge cases like `somesite.com/?json={"this": "is JSON"}`
- Anything else you feel might be useful

**Comment by AnkitaMalik22** [comment]
Hey! I would love to work on this issue! Please assign me .

**Comment by dlford** [comment]
@sanjaybaskaran01 got to it first, sorry @AnkitaMalik22

**Comment by dlford** [comment]
@sanjaybaskaran01 are you still wanting to work on this?

**Comment by nosecreek** [comment]
I can take this @dlford

**Comment by dlford** [comment]
@nosecreek all yours, thanks!
