### ISSUE TITLE
[Req]: Image Tool

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#28]
### Explain the proposed feature

A tool for optimizing and reformatting images.

### Any other details you would like to provide?

This can't likely be done in browser alone, it may be possible to do using server-less functions which should be explored.

This tool should at minimum:
- convert images between jpeg, gif, png, webp, and avif formats
- optionally optimize the image to reduce its size

**Comment by gaston-flores** [comment]
For a low-effort approach, how about using [canvas' `toDataURL`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL)? It supports `png`, `jpeg`, and `webp` as output formats. 

A more complete implementation would use a serverless function to run [sharp](https://github.com/lovell/sharp), but that won't be cheap.

**Comment by dlford** [comment]
@gaston-flores are you wanted to take a crack at the canvas method?

**Comment by gaston-flores** [comment]
Sure!
