### ISSUE TITLE
[Req]: Lorem Ipsum Tool

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#3]
### Explain the proposed feature

Lorem ipsum tool

**Comment by TechSpiritSS** [comment]
May I proceed with this?

**Comment by dlford** [comment]
@TechSpiritSS I have already started on this, but you may pick up where I left off on the `lorem-ipsum-tool` branch if you wish.

**Comment by TechSpiritSS** [comment]
Well in that case, I'll start working on some other tool

**Comment by dlford** [comment]
This has been added.
