### ISSUE TITLE
[OTHER] centre page properly

### ISSUE THREAD

**Issue by Dun-sin** [developertools-tech/developertools.tech#31]
The pages aren't centred properly, don't know if this is intentional or not

Home:
![image](https://user-images.githubusercontent.com/78784850/194227960-5cace8f7-4f0b-4812-b7f5-827563fb19e6.png)

Tools:
![image](https://user-images.githubusercontent.com/78784850/194228309-6cebab4c-0c3e-4eed-bc16-e428ffef71d7.png)

**Comment by dlford** [comment]
@Dun-sin It is intentional, but thanks for calling it out!
