### ISSUE TITLE
[Req]: GH Codespaces / VS Code Remote Container Configuration

### ISSUE THREAD

**Issue by andrewbrey** [developertools-tech/developertools.tech#36]
### Contact Details

GitHub @ message :+1:

### Explain the proposed feature

For `Hacktoberfest`, I have been adding `GitHub Codespaces / VS Code Remote Containers` configuration for OSS projects to make it easier for contributors to the project to get up and running with the correct developer setup. Including the appropriate configuration for a project allows contributors to work entirely within a web browser via GH Codespaces, or inside of fully, and correctly configured containers on their own computer with VS Code Remote Containers (both of these use the same configuration, as GH Codespaces leverages the Remote Containers features under the hood).

For reference, here are two other repositories for whom I've opened PRs to do the same:

- https://github.com/AnilSeervi/inspirational-quotes/pull/19
- https://github.com/Icon-Shelf/icon-shelf/pull/135 (note that this one is a GUI electron app, but it's still possible to containerize it and do development in the cloud on GH Codespaces!)

If you're amenable, I would love to get your project set up with `devcontainer` configuration as well as a `Hacktoberfest` contribution.

### Explain the possible use cases for the feature

Allow contributors to work on the project with the same developer setup, fully built up and completed on their behalf with no work required.

### Any other details you would like to provide?

N/A

**Comment by dlford** [comment]
@andrewbrey Sounds cool, please feel free to proceed.
