### ISSUE TITLE
[Req]: Add search field to nav menu

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#40]
### Explain the proposed feature

Add a search field to the top of the navigation menu

### Explain the possible use cases for the feature

As the list of tools grows, it will become harder to find the tool you want, a search field will help make it easier to find.

### Any other details you would like to provide?

Requirements:
- Add a search field to the top of the navigation menu
- Filter the navigation list as a query is typed
- Enter key should open the top matching nav item when the search field is focused
- Arrow up/down keys should shift focus between the remaining visible nav items when either the search field or a nav item is focused
- Enter key should open a nav item when it is focused

**Comment by V3ntus** [comment]
Hey! I'd like to work on this!

**Comment by amitroy-thedev** [comment]
Will you explain me if a user type something what they're supposed to search from?

**Comment by ElvinPero** [comment]
HI, I could add this feature . can you assign me this.

**Comment by dlford** [comment]
@ElvinPero, sorry but @V3ntus is already working on this one.
