### ISSUE TITLE
[Req]: Improve text diff tool

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#47]
### Explain the proposed feature

The text diff tool (https://www.developertools.tech/text-diff) could be more useful if there were options for different types of text diffing. The package in use has many options and I think we could pass most if not all of them through to the user interface (https://www.npmjs.com/package/diff)

This will of course require new test cases as well.

**Comment by NirvanaPhX** [comment]
Hi Dan, I would like to try this one. Thanks.

**Comment by dlford** [comment]
@NirvanaPhX all yours, thanks!

Feel free to reach out if you have questions.

**Comment by dlford** [comment]
Oh no!, @NirvanaPhX have you started on this yet?

**Comment by dlford** [comment]
Sorry @shu1007!

**Comment by NirvanaPhX** [comment]
Hi Dan. I think I am done function-wise. However, I am not super familiar with testing. Do I have to include a test case for each of the diff function added. Thanks.

**Comment by dlford** [comment]
@NirvanaPhX Yes, I would try to test every use case, take a look at some of the other tests to get an idea, it doesn't have to be perfect or 100% coverage, but enough to raise an alarm if something is broken later on as things change. If in doubt, go ahead and submit your PR and I'll review it for you.
