### ISSUE TITLE
[Req]: HTML Character Codes tool

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#48]
### Explain the proposed feature

A tool to encode and decode all HTML character codes (e.g. `&quot;` <=> `"`) in a string of text.

### Any other details you would like to provide?

This PR should:
- Add to the existing HTML page (use components to keep things clean)
- Provide an "unescaped" and "escaped" field that auto-fills like the Base64 tool and is responsive for mobile devices
- Add new test cases to the `html.spec.tsx` file

**Comment by shu1007** [comment]
Could you please assign it to me?

**Comment by dlford** [comment]
@shu1007 all yours, thanks!
