### ISSUE TITLE
[Req]: Case Converter tool

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#50]
### Explain the proposed feature

A tool that will convert a string of space separated text with the following options:
- Kebab Case => kebab-case
- Camel Case => camelCase
- Pascal Case => PascalCase
- Snake Case => snake_case
- Screaming Snake Case => SCREAMING_SNAKE_CASE
- Screaming Kebab Case => SCREAMING-KEBAB-CASE
- Title Case => Title Case
- Lower Case  => lower case
- Upper Case => UPPER CASE
- Sarcasm Case => SaRcAsM cAsE (because why not?)

### Any other details you would like to provide?

This PR will:
- Create a new `case-converter` tool
- Create tests for the new tool

**Comment by vinayharwani13** [comment]
Hi @dlford, I would like to work on this issue. Could you please assign it to me?

**Comment by dlford** [comment]
@vinayharwani13 all yours, thanks!
