### ISSUE TITLE
[Req]: Improve color tool

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#66]
### Explain the proposed feature

- Add an eye dropper (https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper)
- Add a color preview box to show the selected color

### Any other details you would like to provide?

This PR should:
- Add an eye dropper button conditionally if the browser supports it
- Add a color preview box to show the selected color above or below the color picker with matching styles (gap, border-radius, etc)

**Comment by kubahasek** [comment]
I will take this up! Thank you

**Comment by dlford** [comment]
Awesome, thanks!

**Comment by dlford** [comment]
@kubahasek I'll take a look at this and see if I can find a more performant way, if not we'll drop it.

**Comment by dlford** [comment]
@kubahasek I created a component that leverages the `startTransition` hook to de-prioritize rendering the preview box, let me know how this works for you.

`components/colors/PreviewPane.tsx`

```tsx
import { styled } from '@mui/material/styles';
import React, { startTransition, useEffect } from 'react'

import useLocalState from '../../hooks/useLocalState';

export default function PreviewPane({ color }: { color: string }) {
  const [previewColor, setPreviewColor] = useLocalState<string>({
    key: 'colorPicker_previewColor',
    defaultValue: '#000000',
  });

  useEffect(() => {
    startTransition(() => {
      setPreviewColor(color);
    });
  }, [color, setPreviewColor]);

  const Styled = styled('span')({
    display: 'block',
    backgroundColor: previewColor,
    borderRadius: 8,
    width: '200px',
    height: '100px',
  });

  return <Styled />;
}
```

Using it in `pages/colors.tsx` we can just pass in `pickerColor`.

```tsx
        // ...

        <Box display='flex' flexDirection='column' gap={4}>
          <PreviewPane color={pickerColor} />
          <HexColorPicker
            color={pickerColor}
            onChange={(color) => {
              updateColors({
                target: { name: 'hex', value: color },
              });
            }}
          />
        </Box>

        // ...
```

**Comment by kubahasek** [comment]
@dlford Yep, that's much better! Couldn't have figured that on my own, thanks for teaching me something new again!

Just going to do the eyedropper, and we'll be all done!
