### ISSUE TITLE
[Req]: Character Counter

### ISSUE THREAD

**Issue by kyle-jorve** [developertools-tech/developertools.tech#90]
### Contact Details

kyle.jorve@simpleviewinc.com

### Explain the proposed feature

Add a character counter. We can paste or type text into an input (like a textarea), and the characters will automatically be counted.

### Explain the possible use cases for the feature

We often have to add a description truncation length to collections. This would help with that.

**Comment by dlford** [comment]
@vinayharwani13 all yours, thanks!

**Comment by dlford** [comment]
hey @vinayharwani13, are you still working on this?

**Comment by vinayharwani13** [comment]
Hi @dlford, Sorry did not get time to work on this. I have unassigned myself from this issue.

**Comment by dlford** [comment]
@kyle-jorve how's this? - https://deploy-preview-105--developertools-tech.netlify.app/character-counter

**Comment by kyle-jorve** [comment]
@dlford perfect! Great job! 😀

**Comment by dlford** [comment]
@kyle-jorve deployed! - https://www.developertools.tech/character-counter
