### ISSUE TITLE
[Req]: TOTP Debugger

### ISSUE THREAD

**Issue by dlford** [developertools-tech/developertools.tech#97]
### Explain the proposed feature

A new tool that can generate TOTP secret keys and the OTP codes for them, or accept a user secret.

### Explain the possible use cases for the feature

When developing applications that utilized TOTP, it would be nice to have a web tool instead of enrolling a bunch of temporary secrets for testing

**Comment by mvarrieur** [comment]
@dlford I'd like to take a crack at this one if it's up for grabs?

**Comment by dlford** [comment]
All yours @mvarrieur!
